### ISSUE TITLE
Ability to hide some wrong results from plugins

### ISSUE THREAD

**Issue by patrik-martinko** [Flow-Launcher/Flow.Launcher#1149]
I think that Flow Launcher is great, but it would be nice to have an option to hide some wrong results from plugins.

For example, Window Walker is a very useful plugin, but sometimes shows wrong results like in this example where some background tasks are shown: ApplicationFrameHost.exe, ... (not currently open windows).

![Screenshot 2022-04-24 174205](https://user-images.githubusercontent.com/12855743/164985137-862a9ead-c891-43ec-8354-5483ba3bc994.png)

It would be nice to have an option to hide these results for a user.

**Comment by taooceros** [comment]
It is an enhancement that needs to be addressed in the window walker plugin. I will handle that recently.

**Comment by taooceros** [comment]
this should has been fixed?

**Comment by patrik-martinko** [comment]
I have the latest version of Flow Launcher (v19.3) and Window Walker plugin (v2.0.2) and not opened windows (ApplicationFrameHost.exe) are still in the list. I cannot hide them.
![image](https://user-images.githubusercontent.com/12855743/176994565-334951ad-e0e6-4377-b18b-579b7ed04caf.png)

**Comment by taooceros** [comment]
Please update windowswalker to 2.1.0

**Comment by patrik-martinko** [comment]
I updated to v2.1.0. Still wrong results. The only difference is that it shows me " - Desktop:" after "ApplicationFameHost.exe"
![image](https://user-images.githubusercontent.com/12855743/177554894-02123d86-b005-46d9-97f8-1af55158b45b.png)

**Comment by jjw24** [comment]
Give 2.1.1 a shit please.

**Comment by taooceros** [comment]
I think 2.1.1 hasn't addressed the issue. I will check again about the Settings.

**Comment by taooceros** [comment]
https://github.com/taooceros/Flow.Plugin.WindowWalker/issues/31

**Comment by jjw24** [comment]
WindowWalker v2.1.2 release should address this issue now.
