### ISSUE TITLE
BUG: Explorer Plugin setting working directory seems to have not effect

### ISSUE THREAD

**Issue by guntern** [Flow-Launcher/Flow.Launcher#1779]
### Checks

- [X] I have checked that this issue has not already been reported.

### Problem Description

I am trying to start a python script directly via FlowLauncher. This worked fine with version 1.10 and the everything plugin. But with the new Explorer plugin I run into issues. I added debug output to my python script. And this revealed that it is started with `C:\Windows\system32` as current working directory regardless of whether the corresponding checkbox in the explorer plugin is checked or not.
Is there anything I am missing in the configuration of the Explorer plugin to be able to run my python script directly from FlowLauncher again?
The script launches perfectly fine, when double clicked in Windows Explorer or when invoked via Powershell in its working directory.
The directory containing the script is not in `PATH`.

### To Reproduce

1. Type name of python script in FlowLauncher
2. Hit Enter to run
3. Script reports that it is started with the wrong working directory

### Flow Launcher Version

v1.11.0

### Windows Build Number

10.0.19045.2364

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by deefrawley** [comment]
Hi,
In the settings for the Explorer plugin have you enabled the 'Use search result's l;ocation as the working directory of the executable' under 'General Setting'?

**Comment by guntern** [comment]
Yes I did. I checked with this option enabled and disabled and the python script reported the same working directory in both cases.

**Comment by jjw24** [comment]
> I am trying to start a python script directly via FlowLauncher

How are you running this, just clicking on the result after searching with Explorer? 

Do you have the shebang line in the script? If not I'd imagine you need to put python in front of it file, in this case how are you configure it to launch?

**Comment by taooceros** [comment]
> Yes I did. I checked with this option enabled and disabled and the python script reported the same working directory in both cases.

I just take a look on that setting....and you are right, that's a setting with no effect.

**Comment by guntern** [comment]
> > I am trying to start a python script directly via FlowLauncher
> 
> How are you running this, just clicking on the result after searching with Explorer?
> 
> Do you have the shebang line in the script? If not I'd imagine you need to put python in front of it file, in this case how are you configure it to launch?

I just type part of the file name of the script until it turns up in the search results. Then I just hit Enter. Via the Everything plugin this worked, but not with the new one. Shebang is also included.

Apparently there was an issue with the setting. I am eagerly waiting for the change to end up in my version :-) Hopefully everything is resolved then. Thank you for now in either case.

**Comment by VictoriousRaptor** [comment]
You can try the prerelease by the PR. It should fix this issue.

**Comment by guntern** [comment]
Thank you for the hint. I installed it, but it still reports itself as 1.11.0. How can I ensure that I am actually using this prerelease?
Unfortunately, I cannot ensure it by a working solution. I still have the same issue. But before blaming the solution I doubt my installation process.

By the way here my test python script:

```python
#!python3
import os
import time

print("Flow Launcher Test")
print(os.getcwd())
time.sleep(5)
```

**Comment by VictoriousRaptor** [comment]
> ```python
> #!python3
> import os
> import time
> 
> print("Flow Launcher Test")
> print(os.getcwd())
> time.sleep(5)
> ```

Please try to exit flow and install the preview.

**Comment by taooceros** [comment]
I will check again. I didn't really test the solution since it seems pretty straightforward.

**Comment by VictoriousRaptor** [comment]
https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs#L239-L258

The fix in #1788 is only used when `Ctrl + Shift + Enter` is pressed. But because it runs as admin, cmd's working dir is still set to system32.

**Comment by guntern** [comment]
I tried running using `Ctrl + Shift + Enter`. This seems to try to handle the working directory, but causes another error. Unfortunately I do not directly have the english translation. It is something like: "The file is not assigned to an application". Probably my admin user has not yet chosen to use `py` to run python files. 

Anyway, of course I would prefer to run my file not as admin as it is not needed. I was not able to find the right place to implement a similar solution for non admin running of a file.

**Comment by guntern** [comment]
Its probably the following line which needs to be changed and include the `WorkingDirectory` parameter in the same way as the provided fix, right?
https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs#L152

**Comment by VictoriousRaptor** [comment]
> Its probably the following line which needs to be changed and include the `WorkingDirectory` parameter in the same way as the provided fix, right?
> 
> https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs#L152

Probably. Thank yoiu for locating this problem!

**Comment by guntern** [comment]
I am confused still. The line I found is part of a method, which seems to try to start a file explorer of the selected file. However, somehow it still runs my python file.

https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Flow.Launcher.Plugin/SharedCommands/FilesFolders.cs#L146-L166

The lines shown in https://github.com/Flow-Launcher/Flow.Launcher/issues/1779#issuecomment-1382680344 call `Process.start` on the file itself.

I actually set up Visual Studio and stepped through the code with the debugger. And it is actually the OpenPath-method, which opens my python script, even though from the code I would expect an explorer window.

However, it seems not to be easy to pass the settings of the explorer-Plugin to the OpenPath-method so that it can decided whether or not to use a WorkingDirectory. Maybe one should not end up in the OpenPath-method at all? But my knowledge about the internals of FlowLauncher, the explorer plugin and the intentions appears to be insufficient to judge this completely.

**Comment by taooceros** [comment]
> https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs#L239-L258
> 
> 
> 
> The fix in #1788 is only used when `Ctrl + Shift + Enter` is pressed. But because it runs as admin, cmd's working dir is still set to system32.

Oops my bad sorry about it

**Comment by taooceros** [comment]
The open path is ok because that only applies to folder. I will adjust the file one today

**Comment by guntern** [comment]
> The open path is ok because that only applies to folder. I will adjust the file one today

I really would like to understand why. For me the following line is included in the method `CreateFileResult` and not the `CreateFolderResult`. What am I missing? If this is not the right place to discuss this, we can also switch to discord. I really would like to understand a bit deeper what is going on here.

https://github.com/Flow-Launcher/Flow.Launcher/blob/c136022f7a28c15d061d553d72991a1898103724/Plugins/Flow.Launcher.Plugin.Explorer/Search/ResultManager.cs#L265

**Comment by jjw24** [comment]
Hi @guntern, `CreateFolderResult` uses OpenDirectory here https://github.com/Flow-Launcher/Flow.Launcher/blob/d2cc5760caf70e935065b66a159098442c2520ee/Flow.Launcher/PublicAPIInstance.cs#L198-L208

It takes into consideration of custom explorer setting, where as `OpenPath` does not. I would say we should actually have updated OpenPath with what's in OpenDirectory since it also provides a means to open a file path too. So as it stands, OpenPath should no longer be used since user would want to open a file in their custom explorer too.

**Comment by guntern** [comment]
Unfortunately, I lack the combination of ability and time to look into this issue myself. Is anyone else looking into this? Or am I the only one affected by this issue?

**Comment by taooceros** [comment]
I am so so sorry....my scheduler is broken

**Comment by guntern** [comment]
No stress. It's a free app.
This scheduler thing makes me curious, though.

**Comment by guntern** [comment]
Just received version 1.15
It is working now. Thank you very much 😃
